### PR TITLE
Added ability to dismiss plugins' images Panel by pressing the space bar

### PR DESCRIPTION
**Pull request by pedrovieira7**
While browsing the plugins within Alcatraz I felt the need of closing the plugins' images panel by pressing the space bar, à la Tweetbot, instead of having to esc or cmd+w.  
Let me know if this brings value to you.

### CODE REVIEW

**Comment by pedrovieira7** [comment]
Any feedback?

**Comment by supermarin** [comment]
Hey @pedrovieira7, thanks for your contribution!

I'm okay with the feature, altho the commit seems like it's adding a plenty of more stuff (4 files changed).
Would you mind amending the commit only to include the button section (lines 236-248 in ATZPluginWindowController.xib) and exclude everything else?

**Comment by kattrali** [comment]
Patched and merged in 04fc9087d88c2a618cb1bf256dd58787b02688b3

**Comment by supermarin** [comment]
@kattrali :100: !

**Pull request closed without merging**
