### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Bogidon**
¯\_(ツ)_/¯

### CODE REVIEW

**Comment by guillaume-algis** [comment]
Never gets old :)

Please read the comment just before the line you changed.

**Comment by Bogidon** [comment]
Hahaha, ok. Is the `1` for style? :stuck_out_tongue:

**Comment by guillaume-algis** [comment]
http://knowyourmeme.com/memes/the-1-phenomenon :)

**Comment by Bogidon** [comment]
:ok_hand:

**Comment by Bogidon** [comment]
Some instructions could be added into an [issue template](https://github.com/blog/2111-issue-and-pull-request-templates) to prevent future killjoys.

**Comment by jurre** [comment]
Yes we should, it's already in the [CONTRIBUTING.md](https://github.com/alcatraz/Alcatraz/blob/master/CONTRIBUTING.md) though. Unfortunately hardly anyone reads it

**Pull request closed without merging**
