### PR TITLE
Update copyright year

### PR DESCRIPTION
**Pull request by KishanBagaria**

### CODE REVIEW

**Comment by guillaume-algis** [comment]
👍

**Comment by jurre** [comment]
👍

**Comment by jurre** [comment]
guillaume is missing from the list though!

**Comment by guillaume-algis** [comment]
Ahah 😀
Will do, sir.

**Comment by KishanBagaria** [comment]
@guillaume-algis You are missing from the README.md file too.

**Comment by kattrali** [comment]
This doesn't quite make sense with how copyright works, at least [in the US](https://en.wikipedia.org/wiki/Copyright#Copyright_notices_in_the_United_States), where Alcatraz was originally copyrighted. The year is the first year of publication and the name of authors. There is no need to continually update the year either.

**Comment by KishanBagaria** [comment]
Tbh, I've never understood how copyrights work, and never bothered to look it up.

But, I've observed in thousands of websites (mostly based in US) over the past many years, that people either use the current year, or "(initial/birth year) – (current year)" in the copyright notice. Some even omit the year entirely.

And I've also noticed people making fun of websites where the copyright year is not the current one.

**Pull request merged**
