### PR TITLE
Add automatically generated change log file.

### PR DESCRIPTION
**Pull request by skywinder**
Hi, as I can see, you are carefully fill tags and labels for issues in your repo.

For such cases I create a [github_changelog_generator](https://github.com/skywinder/github-changelog-generator), that generate change log file based on **tags**, **issues** and merged **pull requests** from :octocat: Issue Tracker.

This PR add change log file to your repo (generated by this script).
You can check, how it is look like here: [Change Log](https://github.com/skywinder/Alcatraz/blob/add-change-log-file/CHANGELOG_AUTO.md)

Some essential features, that has this script:

-  it **exclude** not-related to changelog issues (any issue, that has label `question` `duplicate` `invalid` `wontfix` )
- Distinguish issues **according labels**:
    - Merged pull requests (all `merged` pull-requests)
    - Bug fixes (by label `bug` in issue)
    - Enhancements (by label `enhancement` in issue)
    -   Issues (closed issues `w/o any labels`)
- Generate neat Change Log file according basic [change log guidelines](http://keepachangelog.com).

You can easily update this file in future by simply run script: `github_changelog_generator alcatraz/Alcatraz` in your repo folder and it make your Change Log file up-to-date again!

Hope you find this commit as useful. :wink:

P.S.
I know that you already has CHANGELOG.md file but give this script a chance and compare it with yours change log. Hope, you will love it! :blush:

### CODE REVIEW

**Comment by guillaume-algis** [comment]
Thanks for the proposition @skywinder. I feel that Alcatraz is small enough that updating the changelog manually is still doable and will result in a better info/noise ratio.

Thoughts @supermarin @kattrali @jurre ?

**Comment by jurre** [comment]
Agreed

**Comment by skywinder** [comment]
@guillaume-algis Thanks for reply.
Noise can easily eliminated by tagging questions with label "question". 
Any other things, that you assuming as noise?

**Comment by jurre** [comment]
I appreciate the effort you've put in your project @skywinder but right now we don't feel like we need it in Alcatraz. We'll keep it in mind for the future though.

**Pull request closed without merging**
