### PR TITLE
Adds Xcode 8.1 compatibility UUID

### LINKED ISSUE #500: how about xcode-beta 8.1
since we have the xvim way to install alcatraz for xcode 8, can you add 8.1 support?

### PR DESCRIPTION
**Pull request by kaphacius**
Fixes #500

### CODE REVIEW

**Comment by guillaumealgis** [comment]
👍

**Comment by jurre** [comment]
👍 thanks

**Comment by 7934345** [comment]
my xcode 8.1 (unsigned) not working with Alcatraz
I try to reload the plugin by curl -fsSL https://raw.github.com/alcatraz/Alcatraz/master/Scripts/install.sh | sh
but nothing happened. What can i do now?

**Comment by jurre** [comment]
See #475

**Comment by 7934345** [comment]
I read #475 many times, and I dont know what to do now.
Because, Xcode 8.1 has been unsigned by which I download from https://github.com/steakknife/unsign both make and run the unsign blablabla/Xcode

// Unsigned Xcode 
codesign -dv /Applications/Xcode.app/Contents/MacOS/Xcode
reuslt:  
/Applications/Xcode.app/Contents/MacOS/Xcode: code object is not signed at all

// Origin Xcode
codesign -dv /Applications/Xcode.app/Contents/MacOS/Xcode.origin 
result:
Executable=/Applications/Xcode.app/Contents/MacOS/Xcode.origin
Identifier=com.apple.dt.Xcode
Format=Mach-O thin (x86_64)
CodeDirectory v=20200 size=338 flags=0x2200(kill,library-validation) hashes=3+5 location=embedded
Signature size=4605
Info.plist=not bound
TeamIdentifier=59GAB85EFG
Sealed Resources=none
Internal requirements count=1 size=108

**Comment by 7934345** [comment]
Oh....
Stupid!

Plugin info.plist file with wrong ID

	<key>DVTPlugInCompatibilityUUIDs</key>
	<array>
		<string>FEC992CC-CA4A-4CFD-8881-77300FCB848A</string>
		<string>C4A681B0-4A26-480E-93EC-1218098B9AA0</string>
		<string>A2E4D43F-41F4-4FB9-BB94-7177011C9AED</string>
		<string>AD68E85B-441B-4301-B564-A45E4919A6AD</string>
		<string>63FC1C47-140D-42B0-BB4D-A10B2D225574</string>
		<string>37B30044-3B14-46BA-ABAA-F01000C27B63</string>
		<string>640F884E-CE55-4B40-87C0-8869546CAB7A</string>
		<string>992275C1-432A-4CF7-B659-D84ED6D42D3F</string>
		<string>A16FF353-8441-459E-A50C-B071F53F51B7</string>
		<string>9F75337B-21B4-4ADC-B558-F9CADF7073A7</string>
		<string>E969541F-E6F9-4D25-8158-72DC3545A6C6</string>
		<string>8DC44374-2B35-4C57-A6FE-2AD66A36AAD9</string>
		<string>AABB7188-E14E-4433-AD3B-5CD791EAD9A3</string>
		<string>7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90</string>
		<string>0420B86A-AA43-4792-9ED0-6FE0F2B16A13</string>
		<string>CC0D0F4F-05B3-431A-8F33-F84AFCB2C651</string>
		<string>7265231C-39B4-402C-89E1-16167C4CC990</string>
		<string>9AFF134A-08DC-4096-8CEE-62A4BB123046</string>
		<string>F41BD31E-2683-44B8-AE7F-5F09E919790E</string>
		<string>E71C2CFE-BFD8-4044-8F06-00AE685A406C</string>
		<string>ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C</string>
		<string>8A66E736-A720-4B3C-92F1-33D9962C69DF</string>
		<string>65C57D32-1E9B-44B8-8C04-A27BA7AAE2C4</string>
		<string>defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID</string>
	</array>

Sorry, its my fault.

**Comment by ashfurrow** [comment]
This didn't work for me, with Xcode build 8B62. I had to add `DA4FDFD8-C509-4D8B-8B55-84A7B66AE701` to the list of UUIDs manually, and it works 🎉

**Pull request merged**
